# Generated by Django 2.2.7 on 2019-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=30)),
                ('stock_name', models.CharField(max_length=10)),
            ],
        ),
    ]
