# Generated by Django 2.2.7 on 2019-11-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klogin', '0002_scode'),
    ]

    operations = [
        migrations.CreateModel(
            name='predicted_by_ts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('stock_price', models.CharField(max_length=30)),
            ],
        ),
    ]
