# Generated by Django 2.2.7 on 2019-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klogin', '0003_predicted_by_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('stock_code', models.CharField(max_length=10)),
            ],
        ),
    ]
