# Generated by Django 2.2.7 on 2019-11-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klogin', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=3000)),
            ],
        ),
    ]
